### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by hocjordan** [rohit-kumar-j/temporary_pybullet_stub#1]
Hi @rohit-kumar-j, thank you very much for putting up this stub. The pybullet documentation now links to it and it's definitely handy to have.

I have a repo that is using pybullet and I would like to include this stub for people's convenience (crediting you, of course). Would you mind adding a permissive license?

Yours sincerely,
hocjordan

**Comment by rohit-kumar-j** [comment]
Certainly. No probs. 

Edit: Added license.

**Comment by hocjordan** [comment]
Thank you very much!
